import type { NativeStackScreenProps } from '@react-navigation/native-stack';

export type RootStackParamList = {
  Splash: undefined;
  Language: { fromSettings?: boolean } | undefined;
  Welcome: undefined;
  Locality: { fromSettings?: boolean };
  Map: undefined;
  Feed: undefined;
  Feeds: undefined;
  IncidentDetail: { id: string };
  ReportCategory: undefined;
  ReportDetails: { category: string };
  ReportSuccess: { ref: string };
  CrisisReassure: undefined;
  CrisisCategory: undefined;
  CrisisConfirm: { category: string };
  CrisisSuccess: { ref: string };
  FollowUp: { ref: string };
  Inbox: undefined;
  Settings: undefined;
  PrivacyConstitution: undefined;
  HowItWorks: undefined;
  About: undefined;
};

export type SplashProps = NativeStackScreenProps<RootStackParamList, 'Splash'>;
export type LanguageProps = NativeStackScreenProps<RootStackParamList, 'Language'>;
export type WelcomeProps = NativeStackScreenProps<RootStackParamList, 'Welcome'>;
export type LocalityProps = NativeStackScreenProps<RootStackParamList, 'Locality'>;
export type MapProps = NativeStackScreenProps<RootStackParamList, 'Map'>;
export type FeedProps = NativeStackScreenProps<RootStackParamList, 'Feed'>;
export type FeedsProps = NativeStackScreenProps<RootStackParamList, 'Feeds'>;
export type IncidentDetailProps = NativeStackScreenProps<RootStackParamList, 'IncidentDetail'>;
export type SettingsProps = NativeStackScreenProps<RootStackParamList, 'Settings'>;
export type InboxProps = NativeStackScreenProps<RootStackParamList, 'Inbox'>;
export type ReportCategoryProps = NativeStackScreenProps<RootStackParamList, 'ReportCategory'>;
export type ReportDetailsProps = NativeStackScreenProps<RootStackParamList, 'ReportDetails'>;
export type ReportSuccessProps = NativeStackScreenProps<RootStackParamList, 'ReportSuccess'>;
export type CrisisReassureProps = NativeStackScreenProps<RootStackParamList, 'CrisisReassure'>;
export type CrisisCategoryProps = NativeStackScreenProps<RootStackParamList, 'CrisisCategory'>;
export type CrisisConfirmProps = NativeStackScreenProps<RootStackParamList, 'CrisisConfirm'>;
export type CrisisSuccessProps = NativeStackScreenProps<RootStackParamList, 'CrisisSuccess'>;
export type FollowUpProps = NativeStackScreenProps<RootStackParamList, 'FollowUp'>;
