import { I18nManager } from 'react-native';
import type { AppLanguage } from '../types';

export const SUPPORTED_LANGUAGES: AppLanguage[] = ['ar', 'he', 'en'];
export const RTL_LANGUAGES: AppLanguage[] = ['ar', 'he'];

export function isRTL(lang: AppLanguage): boolean {
  return RTL_LANGUAGES.includes(lang);
}

export function applyRTL(lang: AppLanguage): boolean {
  const shouldBeRTL = isRTL(lang);
  if (I18nManager.isRTL !== shouldBeRTL) {
    I18nManager.forceRTL(shouldBeRTL);
    I18nManager.allowRTL(shouldBeRTL);
    return true; // app restart needed to fully apply
  }
  return false;
}

const ar = {
  splash: { error: 'تعذّر تحميل التطبيق', retry: 'إعادة المحاولة' },
  language: {
    title: 'اختر لغتك',
    arabic: 'العربية',
    hebrew: 'עברית',
    english: 'English',
    restartTitle: 'إعادة التشغيل',
    restartMessage: 'يرجى إعادة تشغيل التطبيق لتطبيق اتجاه النص.',
  },
  welcome: {
    slide1: { title: 'بلّغ. شاهد. احمِ', subtitle: 'منصة تقارير مجتمعية فورية لمنطقتك' },
    slide2: { title: 'تنبيهات في نطاقك', subtitle: 'تنبيهات أمنية جغرافية لمنطقتك فور وقوعها' },
    slide3: {
      title: 'خصوصية مطلقة',
      subtitle: 'تقاريرك آمنة تماماً',
      check1: 'لا يُطلب رقم هاتف',
      check2: 'لا علاقة بالشرطة أو أي جهة رسمية',
      check3: 'تقارير مجهولة المصدر بالكامل',
      check4: 'بياناتك تبقى على جهازك فقط',
    },
    next: 'التالي',
    start: 'ابدأ الآن',
  },
  locality: {
    title: 'اختر بلدتك',
    subtitle: 'تُستخدم البلدة فقط لعرض التقارير القريبة — ولا تُشارك مع أي جهة',
    searchPlaceholder: 'ابحث عن بلدتك...',
    cta: 'تفعيل الحساب الآمن',
    selected: 'تم الاختيار',
    noResults: 'لا توجد نتائج مطابقة',
  },
  map: {
    status: { calm: 'هادئ', watch: 'يقظة', active: 'خطر نشط' },
    feed: 'قائمة الحوادث',
    report: 'بلاغ',
  },
  report: {
    title: 'أبلغ عن حادثة',
    categorySubtitle: 'اختر التصنيف الأنسب',
    detailsTitle: 'تفاصيل إضافية',
    detailsPlaceholder: 'اختياري — صف الحادثة باختصار...',
    submit: 'إرسال البلاغ',
    submitting: 'جارٍ الإرسال...',
    successTitle: 'تم إرسال البلاغ',
    successSubtitle: 'شكراً. بلاغك وصل وسيُعرض على المجتمع.',
    refLabel: 'رقم البلاغ',
    copyHint: 'اضغط مطولاً للنسخ',
    backToMap: 'العودة إلى الخريطة',
  },
  crisis: {
    reassureTitle: 'بلاغ فوري',
    reassureSubtitle: 'معلوماتك مجهولة المصدر تماماً ولا تُشارك مع أي جهة',
    reassureCta: 'ابلّغ الآن',
    categoryTitle: 'ما نوع الطوارئ؟',
    confirmTitle: 'تأكيد الإرسال',
    confirmSubtitle: 'سيُرسَل بلاغك من موقعك الحالي',
    send: 'إرسال البلاغ',
    successTitle: 'بلاغك وصل',
    successSubtitle: 'يصل إلى المجتمع الآن. ابقَ بأمان.',
    backToMap: 'العودة إلى الخريطة',
  },
  feed: {
    title: 'حول منطقتك',
    distance: 'ضمن ٣ كم',
    searchPlaceholder: 'ابحث في البلاغات...',
    filters: {
      all: 'الكل',
      reports: 'بلاغات',
      safety: 'إرشادات أمان',
      mediation: 'وساطة',
      initiatives: 'مبادرات',
    },
    empty: 'منطقتك هادئة الآن',
    emptySub: 'لا توجد بلاغات نشطة ضمن ٣ كم من موقعك',
    comments: 'تعليق',
  },
  detail: {
    confirm: 'تأكيد',
    deny: 'نفي',
    alreadyVoted: 'لقد صوّتَّ على هذا البلاغ مسبقاً',
    commentsTitle: 'التعليقات',
    noComments: 'لا توجد تعليقات بعد',
    composerPlaceholder: 'أضف تعليقاً...',
    send: 'إرسال',
    distanceAway: 'على بُعد',
    km: 'كم',
  },
  category: {
    GUNFIRE: 'إطلاق نار',
    STABBING: 'عملية طعن',
    ASSAULT: 'اعتداء جسدي',
    ROBBERY: 'سطو / سرقة',
    SUSPICIOUS: 'نشاط مشبوه',
    OTHER: 'طوارئ أخرى',
  },
  settings: {
    title: 'الإعدادات',
    account: {
      title: 'الحساب',
      locality: 'تغيير البلدة',
      language: 'تغيير اللغة',
      identifier: 'المعرّف العام',
    },
    privacy: {
      title: 'الخصوصية والأمان',
      constitution: 'ميثاق الخصوصية',
      deleteData: 'حذف بياناتي',
      deleteConfirmTitle: 'حذف جميع البيانات؟',
      deleteConfirmMessage: 'سيتم حذف جميع بياناتك من الجهاز والعودة إلى شاشة البداية. هذا الإجراء لا يمكن التراجع عنه.',
      deleteConfirmCancel: 'إلغاء',
      deleteConfirmConfirm: 'حذف',
    },
    notifications: {
      title: 'الإشعارات',
      nearby: 'الحوادث القريبة',
      statusChanges: 'تغييرات حالة المنطقة',
      followUp: 'دعوات المتابعة',
    },
    about: { title: 'حول', version: 'الإصدار' },
    support: { title: 'الدعم', howItWorks: 'كيف يعمل بلاغ؟', contact: 'تواصل معنا' },
  },
  common: {
    retry: 'إعادة المحاولة',
    back: 'رجوع',
    close: 'إغلاق',
    copied: 'تم النسخ',
    loading: 'جارٍ التحميل...',
    error: 'تعذر التحميل',
    networkError: 'تحقّق من اتصالك بالإنترنت ثم أعد المحاولة',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
  },
  errors: {
    generic: 'تعذّر التحميل',
    network: 'تحقّق من اتصالك بالإنترنت ثم أعد المحاولة',
    mapFailed: 'تعذّر تحميل الخريطة',
  },
  offline: {
    banner: 'أنت غير متصل. سيتم إرسال بلاغاتك عند عودة الاتصال.',
    reconnected: 'اتصلت مجدداً. جارٍ إرسال بلاغاتك المعلّقة.',
  },
};

const he: typeof ar = {
  splash: { error: 'לא ניתן לטעון את האפליקציה', retry: 'נסה שוב' },
  language: {
    title: 'בחר שפה',
    arabic: 'العربية',
    hebrew: 'עברית',
    english: 'English',
    restartTitle: 'הפעלה מחדש',
    restartMessage: 'אנא הפעל מחדש את האפליקציה כדי להחיל את כיוון הטקסט.',
  },
  welcome: {
    slide1: { title: 'דווח. צפה. הגן.', subtitle: 'פלטפורמת דיווח קהילתי מיידי לאזורך' },
    slide2: { title: 'התראות באזורך', subtitle: 'התראות ביטחוניות גאוגרפיות לאזורך מיד עם קרות האירוע' },
    slide3: {
      title: 'פרטיות מוחלטת',
      subtitle: 'הדיווחים שלך מאובטחים לחלוטין',
      check1: 'אין צורך במספר טלפון',
      check2: 'אין קשר לרשויות אכיפת החוק',
      check3: 'דיווחים אנונימיים לחלוטין',
      check4: 'המידע שלך נשמר על המכשיר בלבד',
    },
    next: 'הבא',
    start: 'התחל עכשיו',
  },
  locality: {
    title: 'בחר את ישובך',
    subtitle: 'הישוב משמש רק להצגת דיווחים סמוכים — ואינו משותף עם אף גורם',
    searchPlaceholder: 'חפש את ישובך...',
    cta: 'הפעל חשבון מאובטח',
    selected: 'נבחר',
    noResults: 'אין תוצאות תואמות',
  },
  map: {
    status: { calm: 'רגוע', watch: 'ערנות', active: 'סכנה פעילה' },
    feed: 'רשימת אירועים',
    report: 'דיווח',
  },
  report: {
    title: 'דווח על אירוע',
    categorySubtitle: 'בחר את הסיווג המתאים',
    detailsTitle: 'פרטים נוספים',
    detailsPlaceholder: 'אופציונלי — תאר בקצרה...',
    submit: 'שלח דיווח',
    submitting: 'שולח...',
    successTitle: 'הדיווח נשלח',
    successSubtitle: 'תודה. הדיווח שלך התקבל ויוצג לקהילה.',
    refLabel: 'מספר הדיווח',
    copyHint: 'לחץ לחיצה ארוכה להעתקה',
    backToMap: 'חזרה למפה',
  },
  crisis: {
    reassureTitle: 'דיווח מיידי',
    reassureSubtitle: 'המידע שלך אנונימי לחלוטין ואינו משותף עם אף גורם',
    reassureCta: 'דווח עכשיו',
    categoryTitle: 'מה סוג החירום?',
    confirmTitle: 'אישור שליחה',
    confirmSubtitle: 'הדיווח ישלח ממיקומך הנוכחי',
    send: 'שלח דיווח',
    successTitle: 'הדיווח שלך התקבל',
    successSubtitle: 'מגיע לקהילה עכשיו. שמור על עצמך.',
    backToMap: 'חזרה למפה',
  },
  feed: {
    title: 'סביב האזור שלך',
    distance: 'בטווח 3 ק"מ',
    searchPlaceholder: 'חפש בדיווחים...',
    filters: {
      all: 'הכל',
      reports: 'דיווחים',
      safety: 'הנחיות בטיחות',
      mediation: 'גישור',
      initiatives: 'יוזמות',
    },
    empty: 'האזור שלך רגוע כעת',
    emptySub: 'אין דיווחים פעילים בטווח 3 ק"מ ממיקומך',
    comments: 'תגובה',
  },
  detail: {
    confirm: 'אישור',
    deny: 'הכחשה',
    alreadyVoted: 'כבר הצבעת על דיווח זה',
    commentsTitle: 'תגובות',
    noComments: 'אין תגובות עדיין',
    composerPlaceholder: 'הוסף תגובה...',
    send: 'שלח',
    distanceAway: 'במרחק',
    km: 'ק"מ',
  },
  category: {
    GUNFIRE: 'ירי',
    STABBING: 'דקירה',
    ASSAULT: 'תקיפה',
    ROBBERY: 'שוד / גניבה',
    SUSPICIOUS: 'פעילות חשודה',
    OTHER: 'חירום אחר',
  },
  settings: {
    title: 'הגדרות',
    account: { title: 'חשבון', locality: 'שנה ישוב', language: 'שנה שפה', identifier: 'מזהה ציבורי' },
    privacy: {
      title: 'פרטיות ואבטחה',
      constitution: 'מגילת הפרטיות',
      deleteData: 'מחק את הנתונים שלי',
      deleteConfirmTitle: 'למחוק את כל הנתונים?',
      deleteConfirmMessage: 'כל הנתונים שלך יימחקו מהמכשיר ותחזור לסך ההתחלה. פעולה זו אינה ניתנת לביטול.',
      deleteConfirmCancel: 'ביטול',
      deleteConfirmConfirm: 'מחק',
    },
    notifications: { title: 'התראות', nearby: 'אירועים סמוכים', statusChanges: 'שינויי מצב האזור', followUp: 'הזמנות מעקב' },
    about: { title: 'אודות', version: 'גרסה' },
    support: { title: 'תמיכה', howItWorks: "איך בלאג' עובד?", contact: 'צור קשר' },
  },
  common: {
    retry: 'נסה שוב',
    back: 'חזור',
    close: 'סגור',
    copied: 'הועתק',
    loading: 'טוען...',
    error: 'שגיאת טעינה',
    networkError: 'בדוק את חיבור האינטרנט ונסה שוב',
    save: 'שמור',
    cancel: 'ביטול',
    confirm: 'אשר',
  },
  errors: {
    generic: 'לא ניתן לטעון',
    network: 'בדוק את חיבור האינטרנט ונסה שוב',
    mapFailed: 'לא ניתן לטעון את המפה',
  },
  offline: {
    banner: 'אינך מחובר. הדיווחים שלך יישלחו עם חזרת החיבור.',
    reconnected: 'התחברת מחדש. שולח את הדיווחים הממתינים שלך.',
  },
};

const en: typeof ar = {
  splash: { error: 'Failed to load app', retry: 'Retry' },
  language: {
    title: 'Choose your language',
    arabic: 'العربية',
    hebrew: 'עברית',
    english: 'English',
    restartTitle: 'Restart Required',
    restartMessage: 'Please restart the app to apply the text direction.',
  },
  welcome: {
    slide1: { title: 'Report. Watch. Protect.', subtitle: 'Instant community reporting platform for your area' },
    slide2: { title: 'Alerts Where You Are', subtitle: 'Geo-targeted safety alerts for your area as they happen' },
    slide3: {
      title: 'Absolute Privacy',
      subtitle: 'Your reports are completely secure',
      check1: 'No phone number required',
      check2: 'No police or government connection',
      check3: 'Fully anonymous reports',
      check4: 'Data stays on your device only',
    },
    next: 'Next',
    start: 'Get Started',
  },
  locality: {
    title: 'Choose your locality',
    subtitle: 'Your locality is only used to show nearby reports — never shared with any party',
    searchPlaceholder: 'Search for your locality...',
    cta: 'Activate Secure Account',
    selected: 'Selected',
    noResults: 'No matching results',
  },
  map: {
    status: { calm: 'Calm', watch: 'Watch', active: 'Active Danger' },
    feed: 'Incident Feed',
    report: 'Report',
  },
  report: {
    title: 'Report an Incident',
    categorySubtitle: 'Choose the best category',
    detailsTitle: 'Additional Details',
    detailsPlaceholder: 'Optional — briefly describe the incident...',
    submit: 'Submit Report',
    submitting: 'Submitting...',
    successTitle: 'Report Sent',
    successSubtitle: 'Thank you. Your report has been received and will be shown to the community.',
    refLabel: 'Report Number',
    copyHint: 'Long press to copy',
    backToMap: 'Back to Map',
  },
  crisis: {
    reassureTitle: 'Emergency Report',
    reassureSubtitle: 'Your information is completely anonymous and will not be shared with any authority',
    reassureCta: 'Report Now',
    categoryTitle: 'What type of emergency?',
    confirmTitle: 'Confirm Submission',
    confirmSubtitle: 'Your report will be sent from your current location',
    send: 'Send Report',
    successTitle: 'Report Received',
    successSubtitle: 'Reaching the community now. Stay safe.',
    backToMap: 'Back to Map',
  },
  feed: {
    title: 'Around Your Area',
    distance: 'Within 3 km',
    searchPlaceholder: 'Search reports...',
    filters: {
      all: 'All',
      reports: 'Reports',
      safety: 'Safety Tips',
      mediation: 'Mediation',
      initiatives: 'Initiatives',
    },
    empty: 'Your area is calm now',
    emptySub: 'No active reports within 3 km of your location',
    comments: 'comment',
  },
  detail: {
    confirm: 'Confirm',
    deny: 'Deny',
    alreadyVoted: 'You have already voted on this report',
    commentsTitle: 'Comments',
    noComments: 'No comments yet',
    composerPlaceholder: 'Add a comment...',
    send: 'Send',
    distanceAway: 'Away',
    km: 'km',
  },
  category: {
    GUNFIRE: 'Gunfire',
    STABBING: 'Stabbing',
    ASSAULT: 'Assault',
    ROBBERY: 'Robbery',
    SUSPICIOUS: 'Suspicious Activity',
    OTHER: 'Other Emergency',
  },
  settings: {
    title: 'Settings',
    account: { title: 'Account', locality: 'Change Locality', language: 'Change Language', identifier: 'Public Identifier' },
    privacy: {
      title: 'Privacy & Security',
      constitution: 'Privacy Constitution',
      deleteData: 'Delete My Data',
      deleteConfirmTitle: 'Delete all data?',
      deleteConfirmMessage: 'All your data will be deleted from the device and you will return to onboarding. This action cannot be undone.',
      deleteConfirmCancel: 'Cancel',
      deleteConfirmConfirm: 'Delete',
    },
    notifications: { title: 'Notifications', nearby: 'Nearby incidents', statusChanges: 'Area status changes', followUp: 'Follow-up invitations' },
    about: { title: 'About', version: 'Version' },
    support: { title: 'Support', howItWorks: 'How does Balagh work?', contact: 'Contact us' },
  },
  common: {
    retry: 'Retry',
    back: 'Back',
    close: 'Close',
    copied: 'Copied',
    loading: 'Loading...',
    error: 'Failed to load',
    networkError: 'Check your internet connection and try again',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  errors: {
    generic: 'Failed to load',
    network: 'Check your internet connection and try again',
    mapFailed: 'Failed to load map',
  },
  offline: {
    banner: 'You are offline. Reports will be sent when connection is restored.',
    reconnected: 'Reconnected. Sending your pending reports.',
  },
};

export const strings = { ar, he, en } as const;
export type Strings = typeof ar;
