import { I18nManager } from 'react-native';
import type { AppLanguage } from '../types';

export const SUPPORTED_LANGUAGES: AppLanguage[] = ['ar', 'he', 'en'];
export const RTL_LANGUAGES: AppLanguage[] = ['ar', 'he'];

export function isRTL(lang: AppLanguage): boolean {
  return RTL_LANGUAGES.includes(lang);
}

export function applyRTL(lang: AppLanguage): boolean {
  const shouldBeRTL = isRTL(lang);
  if (I18nManager.isRTL !== shouldBeRTL) {
    I18nManager.forceRTL(shouldBeRTL);
    I18nManager.allowRTL(shouldBeRTL);
    return true; // app restart needed to fully apply
  }
  return false;
}

const ar = {
  splash: { error: 'تعذّر تحميل التطبيق', retry: 'إعادة المحاولة' },
  language: {
    title: 'اختر لغتك',
    arabic: 'العربية',
    hebrew: 'עברית',
    english: 'English',
    restartTitle: 'إعادة التشغيل',
    restartMessage: 'يرجى إعادة تشغيل التطبيق لتطبيق اتجاه النص.',
  },
  welcome: {
    slide1: { title: 'بلّغ. شاهد. احمِ', subtitle: 'منصة تقارير مجتمعية فورية لمنطقتك' },
    slide2: { title: 'تنبيهات في نطاقك', subtitle: 'تنبيهات أمنية جغرافية لمنطقتك فور وقوعها' },
    slide3: {
      title: 'خصوصية مطلقة',
      subtitle: 'تقاريرك آمنة تماماً',
      check1: 'لا يُطلب رقم هاتف',
      check2: 'لا علاقة بالشرطة أو أي جهة رسمية',
      check3: 'تقارير مجهولة المصدر بالكامل',
      check4: 'بياناتك تبقى على جهازك فقط',
    },
    next: 'التالي',
    start: 'ابدأ الآن',
  },
  locality: {
    title: 'اختر بلدتك',
    subtitle: 'تُستخدم البلدة فقط لعرض التقارير القريبة — ولا تُشارك مع أي جهة',
    searchPlaceholder: 'ابحث عن بلدتك...',
    cta: 'تفعيل الحساب الآمن',
    selected: 'تم الاختيار',
    noResults: 'لا توجد نتائج مطابقة',
  },
  map: {
    status: { calm: 'هادئ', watch: 'يقظة', active: 'خطر نشط' },
    feed: 'قائمة الحوادث',
    report: 'بلاغ',
    locationDenied: 'لم تُمنح صلاحية الموقع',
    locationDeniedAction: 'الإعدادات',
    longPressForCrisis: 'اضغط مطولاً للبلاغ الفوري',
  },
  report: {
    title: 'أبلغ عن حادثة',
    categorySubtitle: 'اختر التصنيف الأنسب',
    detailsTitle: 'وصف الحالة',
    situationSubtitle: 'اختر الوصف الأقرب لما يحدث',
    situations: {
      GUNFIRE: [
        'سمعت أصوات إطلاق نار في المنطقة',
        'إطلاق نار من سيارة مسرعة',
        'شخص مسلح يطلق النار في الهواء',
        'تبادل إطلاق نار بين عدة أشخاص',
      ],
      STABBING: [
        'شخص تعرّض للطعن ويحتاج مساعدة',
        'شخص يحمل سكيناً ويهدد المارة',
        'مشاجرة تطورت إلى طعن',
        'محاولة طعن دون إصابات',
      ],
      ASSAULT: [
        'اعتداء جسدي على شخص في الشارع',
        'مشاجرة جماعية عنيفة',
        'شخص يضرب آخر ويحتاج الأمر لتدخل',
        'اعتداء بأداة حادة أو عصا',
      ],
      ROBBERY: [
        'سرقة منزل أو محل تجاري',
        'سرقة سيارة أو محاولة سرقتها',
        'سطو مسلح على محل',
        'نشل حقيبة من أحد المارة',
      ],
      SUSPICIOUS: [
        'شخص مجهول يراقب المكان',
        'سيارة مشبوهة تتجول ببطء',
        'شخص يحاول فتح أبواب سيارات أو منازل',
        'جسم أو حقيبة متروكة في مكان عام',
      ],
      OTHER: [
        'حريق أو دخان كثيف',
        'حادث طرق خطير',
        'تجمع متوتر قد يتطور',
        'حالة طارئة أخرى تستدعي الحذر',
      ],
    },
    submit: 'إرسال البلاغ',
    submitting: 'جارٍ الإرسال...',
    successTitle: 'تم إرسال البلاغ',
    successSubtitle: 'شكراً. بلاغك وصل وسيُعرض على المجتمع.',
    refLabel: 'رقم البلاغ',
    copyHint: 'اضغط مطولاً للنسخ',
    backToMap: 'العودة إلى الخريطة',
  },
  crisis: {
    modeBadge: 'وضع الطوارئ',
    reassureTitle: 'بلاغ فوري',
    reassureSubtitle: 'معلوماتك مجهولة المصدر تماماً ولا تُشارك مع أي جهة',
    reassureCta: 'ابلّغ الآن',
    categoryTitle: 'ما نوع الطوارئ؟',
    confirmTitle: 'تأكيد الإرسال',
    confirmSubtitle: 'سيُرسَل بلاغك من موقعك الحالي',
    send: 'إرسال البلاغ',
    successTitle: 'بلاغك وصل',
    successSubtitle: 'يصل إلى المجتمع الآن. ابقَ بأمان.',
    backToMap: 'العودة إلى الخريطة',
  },
  feed: {
    title: 'حول منطقتك',
    distance: 'ضمن ٣ كم',
    searchPlaceholder: 'ابحث في البلاغات...',
    filters: {
      all: 'الكل',
      reports: 'بلاغات',
      safety: 'إرشادات أمان',
      mediation: 'وساطة',
      initiatives: 'مبادرات',
    },
    empty: 'منطقتك هادئة الآن',
    emptySub: 'لا توجد بلاغات نشطة ضمن ٣ كم من موقعك',
  },
  detail: {
    distanceAway: 'على بُعد',
    km: 'كم',
  },
  category: {
    GUNFIRE: 'إطلاق نار',
    STABBING: 'عملية طعن',
    ASSAULT: 'اعتداء جسدي',
    ROBBERY: 'سطو / سرقة',
    SUSPICIOUS: 'نشاط مشبوه',
    OTHER: 'طوارئ أخرى',
  },
  settings: {
    title: 'الإعدادات',
    account: {
      title: 'الحساب',
      locality: 'تغيير البلدة',
      language: 'تغيير اللغة',
      identifier: 'المعرّف العام',
    },
    privacy: {
      title: 'الخصوصية والأمان',
      constitution: 'ميثاق الخصوصية',
      deleteData: 'حذف بياناتي',
      deleteConfirmTitle: 'حذف جميع البيانات؟',
      deleteConfirmMessage: 'سيتم حذف جميع بياناتك من الجهاز والعودة إلى شاشة البداية. هذا الإجراء لا يمكن التراجع عنه.',
      deleteConfirmCancel: 'إلغاء',
      deleteConfirmConfirm: 'حذف',
    },
    notifications: {
      title: 'الإشعارات',
      nearby: 'الحوادث القريبة',
      statusChanges: 'تغييرات حالة المنطقة',
      followUp: 'دعوات المتابعة',
      permissionDenied: 'تعذّر الحصول على إذن الإشعارات. يمكنك تفعيله في إعدادات الجهاز.',
    },
    about: { title: 'حول', version: 'الإصدار' },
    support: { title: 'الدعم', howItWorks: 'كيف يعمل بلاغ؟', contact: 'تواصل معنا' },
  },
  inbox: {
    title: 'الإشعارات',
    empty: 'لا توجد تنبيهات',
    emptySub: 'ستظهر هنا إشعارات الحوادث القريبة وتحديثات بلاغاتك',
    markAllRead: 'قراءة الكل',
    today: 'اليوم',
    yesterday: 'أمس',
    lastWeek: 'هذا الأسبوع',
    notifTypes: {
      nearby: 'حادثة قريبة',
      verification: 'طلب تحقق',
      status: 'تغيير حالة',
      follow_up: 'متابعة',
    },
  },
  followup: {
    title: 'متابعة بلاغك',
    gateQuestion: 'هل أنت بأمان تام حالياً؟',
    safeYes: 'نعم، أنا بأمان',
    safeNo: 'لا، أحتاج مساعدة',
    detailsTitle: 'معلومات إضافية',
    detailsSubtitle: 'جميع الخيارات اختيارية — ساعد المجتمع بما تعرفه',
    vehicleLabel: 'هل كان هناك مركبة؟',
    assailantLabel: 'عدد الأشخاص',
    directionLabel: 'اتجاه الفرار',
    weaponLabel: 'هل كان هناك سلاح؟',
    submitDetails: 'إرسال وإنهاء',
    skip: 'تخطّ',
    yes: 'نعم',
    no: 'لا',
    one: '١',
    two: '٢',
    threePlus: '٣+',
    north: 'شمال',
    south: 'جنوب',
    east: 'شرق',
    west: 'غرب',
    resourcesTitle: 'موارد الطوارئ المدنية',
    resourcesNote: 'لن نسألك أي أسئلة إضافية. سلامتك تأتي أولاً.',
    mdaLabel: 'إسعاف مدى (MDA)',
    mdaNumber: '101',
    civilLabel: 'اللجنة الأهلية في بلدتك',
    civilNote: 'تواصل مع لجنة الحي المحلية للمتابعة المجتمعية والدعم',
    done: 'العودة إلى الخريطة',
    call: 'اتصال',
    followUpCta: 'متابعة البلاغ',
  },
  common: {
    retry: 'إعادة المحاولة',
    back: 'رجوع',
    close: 'إغلاق',
    copied: 'تم النسخ',
    loading: 'جارٍ التحميل...',
    error: 'تعذر التحميل',
    networkError: 'تحقّق من اتصالك بالإنترنت ثم أعد المحاولة',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
  },
  errors: {
    generic: 'تعذّر التحميل',
    network: 'تحقّق من اتصالك بالإنترنت ثم أعد المحاولة',
    mapFailed: 'تعذّر تحميل الخريطة',
  },
  offline: {
    banner: 'أنت غير متصل. سيتم إرسال بلاغاتك عند عودة الاتصال.',
    reconnected: 'اتصلت مجدداً. جارٍ إرسال بلاغاتك المعلّقة.',
  },
  constitution: {
    title: 'ميثاق الخصوصية',
    subtitle: 'سبعة التزامات راسخة — هكذا نحمي هويتك',
    updatedBadge: 'محدّث',
    howWeEnsure: 'كيف نضمن ذلك؟',
    rules: {
      noPersonalData: {
        title: 'لا نجمع أي بيانات شخصية',
        ensure: 'لا يوجد حقل للاسم أو الهاتف أو البريد أو تسجيل الدخول في أي مكان بالتطبيق. الغياب التام لهذه الحقول هو الضمان.',
      },
      noAuthorities: {
        title: 'لا علاقة بالشرطة أو أي جهة رسمية',
        ensure: 'لا يتكامل التطبيق مع أي جهة حكومية أو أمنية. بلاغاتك تُعرض على المجتمع فقط.',
      },
      anonymous: {
        title: 'بلاغاتك مجهولة المصدر بالكامل',
        ensure: 'هويتك مجرد مفتاح عشوائي على جهازك. لا يمكن ربط أي بلاغ بك.',
      },
      onDevice: {
        title: 'بياناتك تبقى على جهازك',
        ensure: 'تُخزَّن إعداداتك ومعرّفك محلياً على الجهاز فقط، ولا تُرفع إلى أي خادم.',
      },
      minimalPermissions: {
        title: 'أذونات الجهاز في حدها الأدنى',
        ensure: 'الموقع أثناء الاستخدام والإنترنت والإشعارات فقط. لا كاميرا ولا ميكروفون ولا صور ولا جهات اتصال.',
      },
      noSound: {
        title: 'صفر صوت — إطلاقاً',
        ensure: 'لا يشغّل التطبيق أي صوت. فحص آلي يمنع إدراج أي ملف صوتي في الكود.',
      },
      openSource: {
        title: 'مفتوح المصدر وقابل للتدقيق',
        ensure: 'الكود متاح للجميع للمراجعة والتحقق من كل ما سبق بأنفسهم.',
      },
    },
  },
  about: {
    title: 'حول بلاغ',
    tagline: 'منصة تقارير مجتمعية تحمي الخصوصية',
    versionLabel: 'الإصدار',
    licenseTitle: 'الرخصة',
    license: 'Apache License 2.0',
    licenseNote: 'هذا التطبيق برمجية حرّة مفتوحة المصدر.',
    sourceTitle: 'الكود المصدري',
    sourceLabel: 'عرض على GitHub',
    acknowledgements: 'شكر وتقدير',
    ossNote: 'بُني بلاغ باستخدام المكتبات مفتوحة المصدر التالية:',
  },
  updateGate: {
    title: 'يلزم تحديث التطبيق',
    message: 'هذه النسخة لم تعد مدعومة. يرجى التحديث للمتابعة باستخدام بلاغ.',
    cta: 'تحديث الآن',
  },
};

const he: typeof ar = {
  splash: { error: 'לא ניתן לטעון את האפליקציה', retry: 'נסה שוב' },
  language: {
    title: 'בחר שפה',
    arabic: 'العربية',
    hebrew: 'עברית',
    english: 'English',
    restartTitle: 'הפעלה מחדש',
    restartMessage: 'אנא הפעל מחדש את האפליקציה כדי להחיל את כיוון הטקסט.',
  },
  welcome: {
    slide1: { title: 'דווח. צפה. הגן.', subtitle: 'פלטפורמת דיווח קהילתי מיידי לאזורך' },
    slide2: { title: 'התראות באזורך', subtitle: 'התראות ביטחוניות גאוגרפיות לאזורך מיד עם קרות האירוע' },
    slide3: {
      title: 'פרטיות מוחלטת',
      subtitle: 'הדיווחים שלך מאובטחים לחלוטין',
      check1: 'אין צורך במספר טלפון',
      check2: 'אין קשר לרשויות אכיפת החוק',
      check3: 'דיווחים אנונימיים לחלוטין',
      check4: 'המידע שלך נשמר על המכשיר בלבד',
    },
    next: 'הבא',
    start: 'התחל עכשיו',
  },
  locality: {
    title: 'בחר את ישובך',
    subtitle: 'הישוב משמש רק להצגת דיווחים סמוכים — ואינו משותף עם אף גורם',
    searchPlaceholder: 'חפש את ישובך...',
    cta: 'הפעל חשבון מאובטח',
    selected: 'נבחר',
    noResults: 'אין תוצאות תואמות',
  },
  map: {
    status: { calm: 'רגוע', watch: 'ערנות', active: 'סכנה פעילה' },
    feed: 'רשימת אירועים',
    report: 'דיווח',
    locationDenied: 'הרשאת מיקום לא ניתנה',
    locationDeniedAction: 'הגדרות',
    longPressForCrisis: 'לחץ לחיצה ארוכה לדיווח מיידי',
  },
  report: {
    title: 'דווח על אירוע',
    categorySubtitle: 'בחר את הסיווג המתאים',
    detailsTitle: 'תיאור המצב',
    situationSubtitle: 'בחר את התיאור הקרוב ביותר למה שקורה',
    situations: {
      GUNFIRE: [
        'נשמעו יריות באזור',
        'ירי מרכב חולף',
        'אדם חמוש יורה באוויר',
        'חילופי ירי בין מספר אנשים',
      ],
      STABBING: [
        'אדם נדקר וזקוק לעזרה',
        'אדם מחזיק סכין ומאיים על עוברי אורח',
        'קטטה שהתדרדרה לדקירה',
        'ניסיון דקירה ללא נפגעים',
      ],
      ASSAULT: [
        'תקיפה פיזית של אדם ברחוב',
        'קטטה המונית אלימה',
        'אדם מכה אחר ונדרשת התערבות',
        'תקיפה עם חפץ חד או מקל',
      ],
      ROBBERY: [
        'פריצה לבית או לחנות',
        'גניבת רכב או ניסיון גניבה',
        'שוד מזוין בחנות',
        'חטיפת תיק מעובר אורח',
      ],
      SUSPICIOUS: [
        'אדם לא מוכר צופה במקום',
        'רכב חשוד נוסע לאט באזור',
        'אדם מנסה לפתוח דלתות רכבים או בתים',
        'חפץ או תיק נטוש במקום ציבורי',
      ],
      OTHER: [
        'שריפה או עשן כבד',
        'תאונת דרכים חמורה',
        'התקהלות מתוחה שעלולה להסלים',
        'מצב חירום אחר המחייב זהירות',
      ],
    },
    submit: 'שלח דיווח',
    submitting: 'שולח...',
    successTitle: 'הדיווח נשלח',
    successSubtitle: 'תודה. הדיווח שלך התקבל ויוצג לקהילה.',
    refLabel: 'מספר הדיווח',
    copyHint: 'לחץ לחיצה ארוכה להעתקה',
    backToMap: 'חזרה למפה',
  },
  crisis: {
    modeBadge: 'מצב חירום',
    reassureTitle: 'דיווח מיידי',
    reassureSubtitle: 'המידע שלך אנונימי לחלוטין ואינו משותף עם אף גורם',
    reassureCta: 'דווח עכשיו',
    categoryTitle: 'מה סוג החירום?',
    confirmTitle: 'אישור שליחה',
    confirmSubtitle: 'הדיווח ישלח ממיקומך הנוכחי',
    send: 'שלח דיווח',
    successTitle: 'הדיווח שלך התקבל',
    successSubtitle: 'מגיע לקהילה עכשיו. שמור על עצמך.',
    backToMap: 'חזרה למפה',
  },
  feed: {
    title: 'סביב האזור שלך',
    distance: 'בטווח 3 ק"מ',
    searchPlaceholder: 'חפש בדיווחים...',
    filters: {
      all: 'הכל',
      reports: 'דיווחים',
      safety: 'הנחיות בטיחות',
      mediation: 'גישור',
      initiatives: 'יוזמות',
    },
    empty: 'האזור שלך רגוע כעת',
    emptySub: 'אין דיווחים פעילים בטווח 3 ק"מ ממיקומך',
  },
  detail: {
    distanceAway: 'במרחק',
    km: 'ק"מ',
  },
  category: {
    GUNFIRE: 'ירי',
    STABBING: 'דקירה',
    ASSAULT: 'תקיפה',
    ROBBERY: 'שוד / גניבה',
    SUSPICIOUS: 'פעילות חשודה',
    OTHER: 'חירום אחר',
  },
  settings: {
    title: 'הגדרות',
    account: { title: 'חשבון', locality: 'שנה ישוב', language: 'שנה שפה', identifier: 'מזהה ציבורי' },
    privacy: {
      title: 'פרטיות ואבטחה',
      constitution: 'מגילת הפרטיות',
      deleteData: 'מחק את הנתונים שלי',
      deleteConfirmTitle: 'למחוק את כל הנתונים?',
      deleteConfirmMessage: 'כל הנתונים שלך יימחקו מהמכשיר ותחזור לסך ההתחלה. פעולה זו אינה ניתנת לביטול.',
      deleteConfirmCancel: 'ביטול',
      deleteConfirmConfirm: 'מחק',
    },
    notifications: { title: 'התראות', nearby: 'אירועים סמוכים', statusChanges: 'שינויי מצב האזור', followUp: 'הזמנות מעקב', permissionDenied: 'לא ניתן לקבל הרשאת התראות. ניתן להפעיל בהגדרות המכשיר.' },
    about: { title: 'אודות', version: 'גרסה' },
    support: { title: 'תמיכה', howItWorks: "איך בלאג' עובד?", contact: 'צור קשר' },
  },
  inbox: {
    title: 'התראות',
    empty: 'אין התראות',
    emptySub: 'כאן יופיעו התראות על אירועים קרובים ועדכוני הדיווחים שלך',
    markAllRead: 'סמן הכל כנקרא',
    today: 'היום',
    yesterday: 'אתמול',
    lastWeek: 'השבוע',
    notifTypes: {
      nearby: 'אירוע קרוב',
      verification: 'בקשת אימות',
      status: 'שינוי מצב',
      follow_up: 'מעקב',
    },
  },
  followup: {
    title: 'מעקב אחר הדיווח שלך',
    gateQuestion: 'האם אתה בטוח לחלוטין כעת?',
    safeYes: 'כן, אני בטוח',
    safeNo: 'לא, אני צריך עזרה',
    detailsTitle: 'מידע נוסף',
    detailsSubtitle: 'כל האפשרויות אופציונליות — עזור לקהילה עם מה שאתה יודע',
    vehicleLabel: 'האם הייתה מעורבת רכב?',
    assailantLabel: 'מספר האנשים',
    directionLabel: 'כיוון הבריחה',
    weaponLabel: 'האם הייתה כלי נשק?',
    submitDetails: 'שלח וסיים',
    skip: 'דלג',
    yes: 'כן',
    no: 'לא',
    one: '1',
    two: '2',
    threePlus: '3+',
    north: 'צפון',
    south: 'דרום',
    east: 'מזרח',
    west: 'מערב',
    resourcesTitle: 'משאבי חירום אזרחיים',
    resourcesNote: 'לא נשאל שאלות נוספות. הבטיחות שלך קודמת.',
    mdaLabel: 'מגן דוד אדום (MDA)',
    mdaNumber: '101',
    civilLabel: 'ועד מקומי ביישובך',
    civilNote: 'פנה לוועד השכונה למעקב קהילתי ולתמיכה',
    done: 'חזרה למפה',
    call: 'חייג',
    followUpCta: 'מעקב אחר הדיווח',
  },
  common: {
    retry: 'נסה שוב',
    back: 'חזור',
    close: 'סגור',
    copied: 'הועתק',
    loading: 'טוען...',
    error: 'שגיאת טעינה',
    networkError: 'בדוק את חיבור האינטרנט ונסה שוב',
    save: 'שמור',
    cancel: 'ביטול',
    confirm: 'אשר',
  },
  errors: {
    generic: 'לא ניתן לטעון',
    network: 'בדוק את חיבור האינטרנט ונסה שוב',
    mapFailed: 'לא ניתן לטעון את המפה',
  },
  offline: {
    banner: 'אינך מחובר. הדיווחים שלך יישלחו עם חזרת החיבור.',
    reconnected: 'התחברת מחדש. שולח את הדיווחים הממתינים שלך.',
  },
  constitution: {
    title: 'מגילת הפרטיות',
    subtitle: 'שבע התחייבויות איתנות — כך אנו מגנים על זהותך',
    updatedBadge: 'עודכן',
    howWeEnsure: 'איך אנו מבטיחים זאת?',
    rules: {
      noPersonalData: {
        title: 'איננו אוספים מידע אישי',
        ensure: 'אין שדה לשם, טלפון, אימייל או התחברות בשום מקום באפליקציה. ההיעדר המוחלט שלהם הוא הערובה.',
      },
      noAuthorities: {
        title: 'אין קשר למשטרה או לרשויות',
        ensure: 'האפליקציה אינה משתלבת עם אף גורם ממשלתי או ביטחוני. הדיווחים שלך מוצגים לקהילה בלבד.',
      },
      anonymous: {
        title: 'הדיווחים שלך אנונימיים לחלוטין',
        ensure: 'הזהות שלך היא מפתח אקראי במכשירך. לא ניתן לקשר אף דיווח אליך.',
      },
      onDevice: {
        title: 'הנתונים שלך נשארים במכשירך',
        ensure: 'ההגדרות והמזהה שלך נשמרים מקומית במכשיר בלבד ואינם נשלחים לאף שרת.',
      },
      minimalPermissions: {
        title: 'הרשאות מכשיר מינימליות',
        ensure: 'מיקום בזמן שימוש, אינטרנט והתראות בלבד. ללא מצלמה, מיקרופון, תמונות או אנשי קשר.',
      },
      noSound: {
        title: 'אפס צליל — אף פעם',
        ensure: 'האפליקציה אינה מנגנת שום צליל. בדיקה אוטומטית מונעת ייבוא של קובץ שמע כלשהו בקוד.',
      },
      openSource: {
        title: 'קוד פתוח וניתן לביקורת',
        ensure: 'הקוד זמין לכולם לבדיקה ולאימות עצמאי של כל האמור לעיל.',
      },
    },
  },
  about: {
    title: "אודות בלאג'",
    tagline: 'פלטפורמת דיווח קהילתי ששומרת על פרטיות',
    versionLabel: 'גרסה',
    licenseTitle: 'רישיון',
    license: 'Apache License 2.0',
    licenseNote: 'אפליקציה זו היא תוכנה חופשית בקוד פתוח.',
    sourceTitle: 'קוד המקור',
    sourceLabel: 'צפה ב-GitHub',
    acknowledgements: 'תודות',
    ossNote: "בלאג' נבנה באמצעות ספריות הקוד הפתוח הבאות:",
  },
  updateGate: {
    title: 'נדרש עדכון לאפליקציה',
    message: 'גרסה זו אינה נתמכת עוד. אנא עדכן כדי להמשיך.',
    cta: 'עדכן עכשיו',
  },
};

const en: typeof ar = {
  splash: { error: 'Failed to load app', retry: 'Retry' },
  language: {
    title: 'Choose your language',
    arabic: 'العربية',
    hebrew: 'עברית',
    english: 'English',
    restartTitle: 'Restart Required',
    restartMessage: 'Please restart the app to apply the text direction.',
  },
  welcome: {
    slide1: { title: 'Report. Watch. Protect.', subtitle: 'Instant community reporting platform for your area' },
    slide2: { title: 'Alerts Where You Are', subtitle: 'Geo-targeted safety alerts for your area as they happen' },
    slide3: {
      title: 'Absolute Privacy',
      subtitle: 'Your reports are completely secure',
      check1: 'No phone number required',
      check2: 'No police or government connection',
      check3: 'Fully anonymous reports',
      check4: 'Data stays on your device only',
    },
    next: 'Next',
    start: 'Get Started',
  },
  locality: {
    title: 'Choose your locality',
    subtitle: 'Your locality is only used to show nearby reports — never shared with any party',
    searchPlaceholder: 'Search for your locality...',
    cta: 'Activate Secure Account',
    selected: 'Selected',
    noResults: 'No matching results',
  },
  map: {
    status: { calm: 'Calm', watch: 'Watch', active: 'Active Danger' },
    feed: 'Incident Feed',
    report: 'Report',
    locationDenied: 'Location permission not granted',
    locationDeniedAction: 'Settings',
    longPressForCrisis: 'Long press for immediate report',
  },
  report: {
    title: 'Report an Incident',
    categorySubtitle: 'Choose the best category',
    detailsTitle: 'Describe the Situation',
    situationSubtitle: 'Pick the description closest to what is happening',
    situations: {
      GUNFIRE: [
        'Heard gunshots in the area',
        'Shots fired from a passing vehicle',
        'Armed person firing into the air',
        'Exchange of gunfire between several people',
      ],
      STABBING: [
        'A person was stabbed and needs help',
        'Person with a knife threatening passersby',
        'A fight escalated into a stabbing',
        'Attempted stabbing, no one hurt',
      ],
      ASSAULT: [
        'Physical assault on someone in the street',
        'Violent group fight',
        'Someone is beating another person, intervention needed',
        'Assault with a sharp object or stick',
      ],
      ROBBERY: [
        'Break-in at a home or shop',
        'Car theft or attempted theft',
        'Armed robbery at a store',
        'Bag snatched from a passerby',
      ],
      SUSPICIOUS: [
        'Unknown person watching the area',
        'Suspicious car driving slowly around',
        'Someone trying car or house doors',
        'Unattended object or bag in a public place',
      ],
      OTHER: [
        'Fire or heavy smoke',
        'Serious road accident',
        'Tense gathering that may escalate',
        'Other emergency requiring caution',
      ],
    },
    submit: 'Submit Report',
    submitting: 'Submitting...',
    successTitle: 'Report Sent',
    successSubtitle: 'Thank you. Your report has been received and will be shown to the community.',
    refLabel: 'Report Number',
    copyHint: 'Long press to copy',
    backToMap: 'Back to Map',
  },
  crisis: {
    modeBadge: 'Emergency Mode',
    reassureTitle: 'Emergency Report',
    reassureSubtitle: 'Your information is completely anonymous and will not be shared with any authority',
    reassureCta: 'Report Now',
    categoryTitle: 'What type of emergency?',
    confirmTitle: 'Confirm Submission',
    confirmSubtitle: 'Your report will be sent from your current location',
    send: 'Send Report',
    successTitle: 'Report Received',
    successSubtitle: 'Reaching the community now. Stay safe.',
    backToMap: 'Back to Map',
  },
  feed: {
    title: 'Around Your Area',
    distance: 'Within 3 km',
    searchPlaceholder: 'Search reports...',
    filters: {
      all: 'All',
      reports: 'Reports',
      safety: 'Safety Tips',
      mediation: 'Mediation',
      initiatives: 'Initiatives',
    },
    empty: 'Your area is calm now',
    emptySub: 'No active reports within 3 km of your location',
  },
  detail: {
    distanceAway: 'Away',
    km: 'km',
  },
  category: {
    GUNFIRE: 'Gunfire',
    STABBING: 'Stabbing',
    ASSAULT: 'Assault',
    ROBBERY: 'Robbery',
    SUSPICIOUS: 'Suspicious Activity',
    OTHER: 'Other Emergency',
  },
  settings: {
    title: 'Settings',
    account: { title: 'Account', locality: 'Change Locality', language: 'Change Language', identifier: 'Public Identifier' },
    privacy: {
      title: 'Privacy & Security',
      constitution: 'Privacy Constitution',
      deleteData: 'Delete My Data',
      deleteConfirmTitle: 'Delete all data?',
      deleteConfirmMessage: 'All your data will be deleted from the device and you will return to onboarding. This action cannot be undone.',
      deleteConfirmCancel: 'Cancel',
      deleteConfirmConfirm: 'Delete',
    },
    notifications: { title: 'Notifications', nearby: 'Nearby incidents', statusChanges: 'Area status changes', followUp: 'Follow-up invitations', permissionDenied: 'Could not get notification permission. You can enable it in device settings.' },
    about: { title: 'About', version: 'Version' },
    support: { title: 'Support', howItWorks: 'How does Balagh work?', contact: 'Contact us' },
  },
  inbox: {
    title: 'Notifications',
    empty: 'No notifications',
    emptySub: 'Nearby incident alerts and report updates will appear here',
    markAllRead: 'Mark all read',
    today: 'Today',
    yesterday: 'Yesterday',
    lastWeek: 'This Week',
    notifTypes: {
      nearby: 'Nearby Incident',
      verification: 'Verification Request',
      status: 'Status Change',
      follow_up: 'Follow-up',
    },
  },
  followup: {
    title: 'Follow up on your report',
    gateQuestion: 'Are you completely safe right now?',
    safeYes: 'Yes, I am safe',
    safeNo: 'No, I need help',
    detailsTitle: 'Additional Information',
    detailsSubtitle: 'All fields are optional — help the community with what you know',
    vehicleLabel: 'Was a vehicle involved?',
    assailantLabel: 'Number of people',
    directionLabel: 'Direction of escape',
    weaponLabel: 'Was a weapon involved?',
    submitDetails: 'Submit & Finish',
    skip: 'Skip',
    yes: 'Yes',
    no: 'No',
    one: '1',
    two: '2',
    threePlus: '3+',
    north: 'North',
    south: 'South',
    east: 'East',
    west: 'West',
    resourcesTitle: 'Civilian Emergency Resources',
    resourcesNote: 'We will not ask any further questions. Your safety comes first.',
    mdaLabel: 'Magen David Adom (MDA)',
    mdaNumber: '101',
    civilLabel: 'Local Community Committee',
    civilNote: 'Reach out to your neighborhood committee for community follow-up and support',
    done: 'Back to Map',
    call: 'Call',
    followUpCta: 'Follow up on report',
  },
  common: {
    retry: 'Retry',
    back: 'Back',
    close: 'Close',
    copied: 'Copied',
    loading: 'Loading...',
    error: 'Failed to load',
    networkError: 'Check your internet connection and try again',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  errors: {
    generic: 'Failed to load',
    network: 'Check your internet connection and try again',
    mapFailed: 'Failed to load map',
  },
  offline: {
    banner: 'You are offline. Reports will be sent when connection is restored.',
    reconnected: 'Reconnected. Sending your pending reports.',
  },
  constitution: {
    title: 'Privacy Constitution',
    subtitle: 'Seven firm commitments — how we protect your identity',
    updatedBadge: 'Updated',
    howWeEnsure: 'How do we ensure this?',
    rules: {
      noPersonalData: {
        title: 'We collect no personal data',
        ensure: 'There is no name, phone, email, or login field anywhere in the app. Their complete absence is the guarantee.',
      },
      noAuthorities: {
        title: 'No police or government connection',
        ensure: 'The app does not integrate with any government or security authority. Your reports are shown to the community only.',
      },
      anonymous: {
        title: 'Your reports are fully anonymous',
        ensure: 'Your identity is just a random key on your device. No report can be linked back to you.',
      },
      onDevice: {
        title: 'Your data stays on your device',
        ensure: 'Your settings and identifier are stored locally on the device only, never uploaded to any server.',
      },
      minimalPermissions: {
        title: 'Minimal device permissions',
        ensure: 'Only location while-in-use, internet, and notifications. No camera, microphone, photos, or contacts.',
      },
      noSound: {
        title: 'Zero sound — ever',
        ensure: 'The app plays no audio. An automated check prevents importing any audio file in the code.',
      },
      openSource: {
        title: 'Open source and auditable',
        ensure: 'The code is available for anyone to review and verify all of the above for themselves.',
      },
    },
  },
  about: {
    title: 'About Balagh',
    tagline: 'A privacy-protecting community reporting platform',
    versionLabel: 'Version',
    licenseTitle: 'License',
    license: 'Apache License 2.0',
    licenseNote: 'This app is free and open-source software.',
    sourceTitle: 'Source Code',
    sourceLabel: 'View on GitHub',
    acknowledgements: 'Acknowledgements',
    ossNote: 'Balagh is built with the following open-source libraries:',
  },
  updateGate: {
    title: 'App Update Required',
    message: 'This version is no longer supported. Please update to continue using Balagh.',
    cta: 'Update Now',
  },
};

export const strings = { ar, he, en } as const;
export type Strings = typeof ar;
